management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env", "metrics", "prometheus", "health", "info", "threaddump", "mappings"]
server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

---

spring:
  config:
    activate:
      on-profile:
        - test
  datasource:
    url: jdbc:tc:postgresql:///testdb?TC_IMAGE_TAG=14-alpine
  jpa:
    hibernate:
      ddl-auto: update
---